In [1]:
import numpy as np

## DataType & Attributes

In [2]:
# Numpy's main datatype is ndarray(n dimensional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0,10,size = (3,5))

In [25]:
random_array

array([[2, 0, 4, 6, 7],
       [2, 9, 3, 7, 2],
       [1, 8, 2, 4, 7]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random2_array = np.random.randint(0,10)

In [31]:
type(random2_array)

int

In [36]:
random_array_2 = np.random.random((5,3))
random_array_2 

array([[0.33550882, 0.4032366 , 0.38822413],
       [0.17450222, 0.13806204, 0.34420284],
       [0.99915615, 0.18862317, 0.9534453 ],
       [0.09501138, 0.67799774, 0.08832948],
       [0.81346307, 0.97495255, 0.02631427]])

In [37]:
random_array_2.shape

(5, 3)

In [43]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.581541  , 0.89445963, 0.79160152],
       [0.56942116, 0.74140602, 0.96955545],
       [0.67355814, 0.33799834, 0.19305248],
       [0.17705223, 0.13121601, 0.16755634],
       [0.4498799 , 0.70436615, 0.77681014]])

In [50]:
# Pseudo-random numbers
np.random.seed(seed=46)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 8, 4],
       [3, 2, 0],
       [2, 8, 0],
       [7, 6, 2],
       [2, 2, 2]])

In [55]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [52]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [56]:
np.unique(random_array_4)

array([0, 2, 3, 4, 5, 6, 7, 8])

In [57]:
a1

array([1, 2, 3])

In [58]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [59]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [60]:
a1[0]

1

In [63]:
a2.shape

(2, 3)

In [61]:
a2[0]

array([1., 2., 3.])

In [64]:
a3.shape

(2, 3, 3)

In [65]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [67]:
a2[1]

array([4. , 5. , 6.5])

In [68]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [69]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [70]:
a4 = np.random.randint(10,size = (2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [72]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [75]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Mainpulating & Comparing arrays

### Artihmetic

In [76]:
a1

array([1, 2, 3])

In [78]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [79]:
a1 + ones

array([2., 3., 4.])

In [80]:
a1 - ones

array([0., 1., 2.])

In [81]:
a1 * ones

array([1., 2., 3.])

In [84]:
a1

array([1, 2, 3])

In [82]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [83]:
a2 * a1

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [85]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [86]:
# How can you reshape a2 to be compatible with a3?
# Search : "How to reshape numpy array"
a3 * a2

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [87]:
a1 / ones

array([1., 2., 3.])

In [89]:
a2 /a1

array([[1.        , 1.        , 1.        ],
       [4.        , 2.5       , 2.16666667]])

In [88]:
# Floor division removes the decimals(rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [91]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [90]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [92]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [93]:
np.add(a1,ones)

array([2., 3., 4.])

In [94]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [95]:
a1 /2

array([0.5, 1. , 1.5])

In [96]:
a2 % 2

array([[1. , 0. , 1. ],
       [0. , 1. , 0.5]])

In [97]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [98]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggreation

Aggregation = performing the same operation on a number of things

In [100]:
listy_list = [1,2,3]
type(listy_list)

list

In [101]:
sum(listy_list)

6

In [102]:
a1

array([1, 2, 3])

In [104]:
sum(a1)

6

In [105]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use
NumPy's menthods on Numpy arrays(`np.sum()`).

In [106]:
# Creative a massive Numpy array
massive_array = np.random.random(10000)
massive_array.size

10000

In [108]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [109]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

676 µs ± 30 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
6.37 µs ± 67.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [110]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [111]:
np.mean(a2)

3.5833333333333335

In [112]:
np.max(a2)

6.5

In [113]:
np.min(a2)

1.0

In [114]:
# Standard deviation = a measure of ho w spread out a group of numbers is from the mean
np.std(a2)

1.8352262954621035

In [115]:
# Variance = measure of the average degree to which each number is differnet to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.368055555555556

In [116]:
# Standard eviation = sqrt of vraince
np.sqrt(np.var(a2))

1.8352262954621035