In [70]:
import numpy as np

## DataType & Attributes

In [71]:
# Numpy's main datatype is ndarray(n dimensional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [72]:
type(a1)

numpy.ndarray

In [73]:
a2 = np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [74]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a1.shape

(3,)

In [77]:
a2.shape

(2, 3)

In [78]:
a3.shape

(2, 3, 3)

In [79]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [80]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [81]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [82]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [83]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [84]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [85]:
sample_array.dtype

dtype('int32')

In [86]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
ones.dtype

dtype('float64')

In [88]:
type(ones)

numpy.ndarray

In [89]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [91]:
random_array = np.random.randint(0,10,size = (3,5))

In [92]:
random_array

array([[0, 5, 3, 0, 5],
       [7, 1, 8, 4, 9],
       [0, 2, 0, 7, 6]])

In [93]:
random_array.size

15

In [94]:
random_array.shape

(3, 5)

In [95]:
random2_array = np.random.randint(0,10)

In [96]:
type(random2_array)

int

In [97]:
random_array_2 = np.random.random((5,3))
random_array_2 

array([[0.79695136, 0.97513968, 0.27425859],
       [0.16910106, 0.87670093, 0.90918246],
       [0.19753289, 0.44152974, 0.71923214],
       [0.84534516, 0.16827531, 0.66496896],
       [0.80783546, 0.54971412, 0.16471666]])

In [98]:
random_array_2.shape

(5, 3)

In [99]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.0355288 , 0.28153382, 0.80787085],
       [0.04476626, 0.00821651, 0.36161665],
       [0.06362229, 0.1494863 , 0.02319037],
       [0.52471984, 0.6966959 , 0.42705349],
       [0.13457046, 0.33135721, 0.59034585]])

In [100]:
# Pseudo-random numbers
np.random.seed(seed=46)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 8, 4],
       [3, 2, 0],
       [2, 8, 0],
       [7, 6, 2],
       [2, 2, 2]])

In [101]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [102]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [103]:
np.unique(random_array_4)

array([0, 2, 3, 4, 5, 6, 7, 8])

In [104]:
a1

array([1, 2, 3])

In [105]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [106]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [107]:
a1[0]

1

In [108]:
a2.shape

(2, 3)

In [109]:
a2[0]

array([1. , 2. , 3.3])

In [110]:
a3.shape

(2, 3, 3)

In [111]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [113]:
a2[1]

array([4. , 5. , 6.5])

In [114]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [115]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [116]:
a4 = np.random.randint(10,size = (2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [117]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [118]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Mainpulating & Comparing arrays

### Artihmetic

In [119]:
a1

array([1, 2, 3])

In [120]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [121]:
a1 + ones

array([2., 3., 4.])

In [122]:
a1 - ones

array([0., 1., 2.])

In [123]:
a1 * ones

array([1., 2., 3.])

In [124]:
a1

array([1, 2, 3])

In [125]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [126]:
a2 * a1

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [127]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [128]:
# How can you reshape a2 to be compatible with a3?
# Search : "How to reshape numpy array"
a3 * a2

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [ ]:
a1 / ones

In [ ]:
a2 /a1

In [ ]:
# Floor division removes the decimals(rounds down)
a2 // a1

In [ ]:
a2

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1,ones)

In [ ]:
a1 % 2

In [ ]:
a1 /2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggreation

Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

Use Python's methods (`sum()`) on Python datatypes and use
NumPy's menthods on Numpy arrays(`np.sum()`).

In [ ]:
# Creative a massive Numpy array
massive_array = np.random.random(10000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a measure of ho w spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is differnet to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard eviation = sqrt of vraince
np.sqrt(np.var(a2))

In [ ]:
#Demo of std and var
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
#%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshaping & Transposing

In [129]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [130]:
a2.shape

(2, 3)

In [131]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [132]:
a3.shape

(2, 3, 3)

In [133]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [136]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [137]:
a3.shape

(2, 3, 3)

In [138]:
a2_reshape = a2.reshape(2,3,1) 

In [139]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [141]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [140]:
#transpose = switches the axis
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [142]:
a2.T.shape

(3, 2)

In [143]:
a3.shape

(2, 3, 3)

In [144]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [145]:
a3.T.shape

(3, 3, 2)

## Dot Product

In [148]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [149]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [150]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [151]:
# Element-wise multiplication hadamard product
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [153]:
# Dot product
#np.dot(mat1,mat2)

In [154]:
# Trnaspose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [156]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [158]:
mat3 = np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [159]:
mat3.shape

(5, 5)

## Dot product example(nut butter sales)

In [160]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [161]:
#create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tues","Wed","Thu","Fri"],
                                            columns = ["Alomnd butter","Peanut butter", "Carshew butter"])
weekly_sales

Alomnd butter  Peanut butter  Carshew butter
Mon              12             15               0
Tues              3              3               7
Wed               9             19              18
Thu               4              6              12
Fri               1              6               7

In [162]:
#create price array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [164]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"],columns = ["Alomnd butter","Peanut butter", "Carshew butter"])
butter_prices

Alomnd butter  Peanut butter  Carshew butter
Price             10              8              12

In [168]:
prices.shape

(3,)

In [169]:
sales_amounts.shape

(5, 3)

In [170]:
# Shape aren't aligned, we need to transposed
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [173]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [175]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thu  Fri
Price  240   138  458  232  142

In [176]:
weekly_sales["Total($)"] = daily_sales.T
weekly_sales

Alomnd butter  Peanut butter  Carshew butter  Total($)
Mon              12             15               0       240
Tues              3              3               7       138
Wed               9             19              18       458
Thu               4              6              12       232
Fri               1              6               7       142

### Comparison Operators

In [177]:
a1

array([1, 2, 3])

In [178]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [179]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [180]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [181]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [182]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [183]:
a1 > 5

array([False, False, False])

In [184]:
a1 < 5

array([ True,  True,  True])

In [185]:
a1 == a1

array([ True,  True,  True])

In [186]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## 5. Sorting array

In [190]:
random_array = np.random.randint(10,size = (3,5))
random_array

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [191]:
# sorting by the number values
np.sort(random_array)

array([[0, 0, 2, 4, 7],
       [4, 5, 5, 6, 8],
       [1, 1, 4, 8, 9]])

In [192]:
# showing by the index
np.argsort(random_array)

array([[2, 3, 1, 4, 0],
       [4, 0, 1, 2, 3],
       [0, 4, 1, 3, 2]], dtype=int64)

In [193]:
a1

array([1, 2, 3])

In [194]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [195]:
np.argmin(a1)

0

In [196]:
random_array

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [198]:
# return the index of the higest number from the row
np.argmax(random_array, axis=0)

array([0, 1, 2, 1, 0], dtype=int64)

In [199]:
# return the index of the higest number from the column
np.argmax(random_array, axis=1)

array([0, 3, 2], dtype=int64)

## 6. Practical Example - Numpy in Action!!!!

<img src="img/panda.png"/>

In [202]:
# Trun an image into a Numpy array
from matplotlib.image import imread

panda = imread("img/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [204]:
panda.size,panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)

In [206]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="img/car-photo.png" />

In [208]:
car = imread("img/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [210]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)